name: Monorepo Release and Update Changelog
on:
  push:
    branches:
      - feature/**
      - fix/**
      - hotfix/**
      - release/**
      - refactor/**

jobs:
  get_apps:
    runs-on: ubuntu-latest
    outputs:
      applications: ${{ steps.filter.outputs.changes }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - uses: dorny/paths-filter@v2
        id: filter
        with:
          filters: |
            engine/core: 'engine/core/**'
            engine/monitor: 'engine/monitor/**'
            engine/realtime: 'engine/realtime/**'
            engine/scheduler: 'engine/scheduler/**'
            engine/worker: 'engine/worker/**'
            platform/core: 'platform/core/**'
            platform/sync: 'platform/sync/**'
            platform/worker: 'platform/worker/**'
            studio: 'studio/**'

  build:
    runs-on: ubuntu-latest
    needs: get_apps
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14

      - name: Install Dependencies
        run: npm ci

      - name: Install lerna
        run: npm i -g lerna

      - name: Check for changes and update versions
        run: |
          packages=$(echo "${{ needs.get_apps.outputs.applications }}" | tr -d '[]' | tr -d '"')
          echo "Found changes in packages: $packages"
          all_changes=""
          overall_version=""
          for package in ${packages[@]}; do
            cd $package
            echo "Checking changes for $package..."
            result=$(git diff --name-only origin/master..HEAD . | wc -l)
            echo "Changes found: $result"
            if [ "$result" -gt "0" ]; then
              echo "$package has changes. Updating version..."
              npm ci
              npm version patch --no-git-tag-version
              version=$(cat package.json | jq -r '.version')
              git add package.json

              changelog=$(npx conventional-changelog -p angular -i CHANGELOG.md -s)
              all_changes+="# $package $version\n"
              all_changes+="$changelog\n\n"
              overall_version="$version"
            fi
            cd -
          done
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git commit -m "chore(release): $version [skip ci]"
          echo "Generating changelog for $package"
          echo "::set-output name=all_changes::$all_changes"
          echo "::set-output name=overall_version::$overall_version"
        id: version_changelog

      - name: Update overall version
        run: |
          echo "Updating overall version..."
          echo "::set-output name=overall_version::$(npm version patch --no-git-tag-version)"
        id: overall_version

      - name: Update overall changelog
        run: |
          echo "${{ steps.version_changelog.outputs.all_changes }}" >> CHANGELOG.md
          git add CHANGELOG.md
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git commit -am "Update CHANGELOG.md [skip ci]"
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref }}

      - name: Create tag
        run: git tag v${{ steps.overall_version.outputs.overall_version }}

      - name: Push tag
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          tags: true

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: v${{ steps.overall_version.outputs.overall_version }}
          release_name: Release v${{ steps.overall_version.outputs.overall_version }}
          body: ${{ steps.version_changelog.outputs.all_changes }}
          draft: false
          prerelease: false
